{{ if .Values.configSecret.create }}
{{- $unused := required "You must set a Cherry Servers API key" .Values.config.apiKey -}}
{{- $unused := required "You must set an Cherry Servers project ID" .Values.config.projectID -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloud-provider-cherry.configSecretName" . }}
  labels:
    {{- include "cloud-provider-cherry.labels" . | nindent 4 }}
type: Opaque
data:
  cloud-sa.json: {{ .Values.config | toJson | b64enc | quote }}
{{ end }}
