name: Backport
on:
  pull_request_target:
    types:
      - closed

permissions:
  pull-requests: write
  contents: write

jobs:
  backport:
    name: Backport pull request
    runs-on: ubuntu-latest
    # Only run on merged PRs.
    if: github.event.pull_request.merged
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Create backport pull requests
        uses: korthout/backport-action@01619ebc9a6e3f6820274221b9956b3e7365000a # v4.1.0
