name: Release
on:
  push:
    tags:
    - 'v*'
permissions:
  contents: read
  packages: read

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  images: # create images in docker hub
    name: Images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Set up QEMU for cross-building
      uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

    - name: Build image urls
      id: image-urls
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        IMAGES=ghcr.io/${IMAGE_NAME}
        [[ -n "$DOCKER_USERNAME" ]] && IMAGES=${IMAGES},${IMAGE_NAME}
        echo "images=${IMAGES}" >> $GITHUB_OUTPUT 

    - name: Docker manager metadata
      id: meta
      uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
      with:
        images: ${{ steps.image-urls.outputs.images }}
        tags: |
          type=ref,event=tag

    - name: Log in to ghcr.io
      uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Log into DockerHub
      uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      if: ${{ env.DOCKER_USERNAME != '' }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build
      id: docker_build
      uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
      env:
        VERSION: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
      with:
        context: .
        push: true
        build-args: |
          BINARY=cloud-provider-cherry
          LDFLAGS=-X 'k8s.io/component-base/version.gitVersion=${{ env.VERSION }}' -X 'k8s.io/component-base/version/verflag.programName=Cloud Provider Cherry Servers'
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha, scope=${{ github.workflow }}
        cache-to: type=gha, mode=max, scope=${{ github.workflow }}

  release: # create a github actions release with necessary artifacts
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
    - images
    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Build image urls
      id: image-urls
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        IMAGES=ghcr.io/${IMAGE_NAME}
        [[ -n "$DOCKER_USERNAME" ]] && IMAGES=${IMAGES},${IMAGE_NAME}
        echo "images=${IMAGES}" >> $GITHUB_OUTPUT 

    - name: Docker manager metadata
      id: meta
      uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
      with:
        images: ${{ steps.image-urls.outputs.images }}
        tags: |
          type=ref,event=tag

    - name: release template
      env:
        RELEASE_IMG: ghcr.io/${{ env.IMAGE_NAME }}:${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
      run: cat deploy/template/deployment.yaml | sed 's#RELEASE_IMG#${{ env.RELEASE_IMG }}#g' > /tmp/deployment.yaml

    - name: Set default release note
      run: echo 'RELEASE_NOTES=Compatibility with matching k8s version.' >> $GITHUB_ENV

    # patch-like just means a non-zero Z in vX.Y.Z, since we don't strictly adhere to semver.
    - name: Check if patch-like release
      id: release-ver
      run: | 
        TAG="${GITHUB_REF#refs/tags/}"

        if [[ "$TAG" =~ ^v[0-9]+\.[0-9]+\.[1-9][0-9]*$ ]]; then
          echo "is_patch=true" >> "$GITHUB_OUTPUT"
        else
          echo "is_patch=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Generate patch-like release notes
      if: steps.release-ver.outputs.is_patch == 'true'
      run: |
        release_notes=$(gh api repos/{owner}/{repo}/releases/generate-notes -F tag_name=${{ github.ref }} --jq .body)
        echo 'RELEASE_NOTES<<EOF' >> $GITHUB_ENV
        echo "${release_notes}" >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OWNER: ${{ github.repository_owner }}
        REPO: ${{ github.event.repository.name }}

    - name: Create Release
      uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: /tmp/deployment.yaml
        body: ${{ env.RELEASE_NOTES }}
        draft: false
        prerelease: false
